---
title: "Technical File: Time Series Analysis of State Tract-level Data"
author: 
- "Nathan Alexander, PhD"
- "Ethan Gwinn"
- "Howard University"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true  # Enable floating TOC in the sidebar
    number_sections: true
    theme: cerulean
    always_allow_html: true
    self_contained: true
editor_options:
  markdown:
    wrap: sentence
---

# Project setup

```{r setup, include=F, warning=F, message=F}
knitr::opts_chunk$set(echo = TRUE)
library(here)
here::i_am("technical-file-time-series-tract.Rmd")

# install packages
#install.packages("tidycensus")
#install.packages("tidyverse")
#install.packages("mapview")
#install.packages("mapgl")
library(tidycensus)
library(dplyr)
library(ggplot2)
library(sf)
library(viridis)
library(scales)
library(readr)

```

# Data import

We'll first search for all variables.

https://api.census.gov/data.html

```{r, eval=F, message=F, warning=F}
vars2020 <- load_variables(2020, "dhc")

View(vars2020)
```


We will start with importing race vars.

```{r, message=F, warning=F}
vars <- c(
  total = "P10_001N",
  white = "P10_003N",
  black = "P10_004N"
)

```

Then we'll pull in data for Mobile, AL.

```{r, message=F, warning=F}
mob_pop_2020 <- get_decennial(
  geography = "county",
  variables = "P1_001N",
  state = "AL",
  sumfile = "dhc",
  year = 2020
) %>% 
  filter(NAME == "Mobile County, Alabama")

mob_pop_2020
```


```{r, message=F, warning=F}
mob_pop_2010 <- get_decennial(
  geography = "county",
  variables = "P001001", 
  state = "AL",
  year = 2010,
  sumfile = "sf1"
) %>% 
  filter(NAME == "Mobile County, Alabama")

mob_pop_2010
```

```{r, message=F, warning=F}
mob_pop_2000 <- get_decennial(
  geography = "county",
  variables = "P001001", 
  state = "AL",
  year = 2000,
  sumfile = "sf1"
) %>% 
  filter(NAME == "Mobile County, Alabama")

mob_pop_2000
```

# Merging data

```{r, message=F, warning=F}
county_joined <- mob_pop_2020 %>% 
  select(GEOID, NAME, value20 = value) %>% 
  left_join(mob_pop_2010, by = "GEOID") %>% 
  mutate(total_change = value20 - value,
         percent_change = 100 * (total_change / value))

county_joined
```


# Time Series

```{r, message=F, warning=F}
ts_data <- read.csv("../../data/time-series/time-series-csv/nhgis0009_ts_nominal_tract.csv")

str(ts_data)
#View(ts_data)
```

```{r, message=F, warning=F}
library(dplyr)

ts_clean <- ts_data %>%
  select(
    NHGISCODE,
    STATE,
    STATEFP,
    COUNTY,
    total_1980 = B18AA1980,
    total_1990 = B18AA1990,
    total_2000 = B18AA2000,
    total_2010 = B18AA2010,
    
    white_1980 = B18AB1980,
    white_1990 = B18AB1990,
    white_2000 = B18AB2000,
    white_2010 = B18AB2010,
    
    black_1980 = B18AC1980,
    black_1990 = B18AC1990,
    black_2000 = B18AC2000,
    black_2010 = B18AC2010
  )

ts_clean
```


```{r, message=F, warning=F}
mobile_ts <- ts_clean %>%
  filter(STATE == "Alabama", COUNTY == "Mobile County")

summary(mobile_ts)
```


```{r, message=F, warning=F}
library(tidyr)

ts_long <- mobile_ts %>%
  pivot_longer(
    cols = matches("^(total|white|black)_"),
    names_to = c("variable", "year"),
    names_sep = "_",
    values_to = "value"
  )

str(ts_long)

```

```{r, message=F, warning=F}
ts_final <- ts_long %>%
  pivot_wider(names_from = variable, values_from = value) %>%
  mutate(
    year = as.numeric(year),
    pct_black = black / total
  ) %>%
  filter(!is.na(total))

str(ts_final)
```

```{r, include=F, message=F, warning=F}
# check for internal consistency
ts_final %>%
  group_by(year) %>%
  summarise(
    total_black = sum(black, na.rm = TRUE),
    total_white = sum(white, na.rm = TRUE),
    total_pop   = sum(total, na.rm = TRUE)
  )
```

# Dissimilarity Index

```{r, message=F, warning=F}
library(dplyr)

dissimilarity <- ts_final %>%
  group_by(year) %>%
  summarise(
    B = sum(black, na.rm = TRUE),
    W = sum(white, na.rm = TRUE),
    
    D = 0.5 * sum(
      abs((black / sum(black, na.rm = TRUE)) -
          (white / sum(white, na.rm = TRUE))),
      na.rm = TRUE
    )
  )

dissimilarity
```

```{r, message=F, warning=F}
library(ggplot2)
library(scales)

ggplot(dissimilarity, aes(x = year, y = D)) +
  geom_line(linewidth = 1.4, color = "#2C3E50") +
  geom_point(size = 3, color = "#E74C3C") +
  
  # Add value labels
  geom_text(
    aes(label = scales::percent(D, accuracy = 0.1)),
    vjust = -1,
    size = 4,
    color = "black"
  ) +
  
  scale_y_continuous(
    labels = percent_format(accuracy = 1),
    limits = c(0, max(dissimilarity$D, na.rm = TRUE) + 0.05),
    expand = expansion(mult = c(0.02, 0.1))
  ) +
  
  scale_x_continuous(
    breaks = dissimilarity$year
  ) +
  
  labs(
    title = "Black–White Segregation Estimates for Mobile County, AL",
    x = "Year",
    y = "Index of Dissimilarity"
  ) +
  
  theme_minimal(base_size = 13) +
  theme(
    plot.title = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  )
```




```{r, eval=F, message=F, warning=F}
ggsave(
  filename = "img/dissimilarity_mobile_1980_2010.png",
  width = 7,
  height = 5,
  dpi = 300
)
```

# 1980s map (tract-level)

```{r, message=F, warning=F}
library(sf)

tracts_1980 <- st_read("../../data/time-series/1980shape/nhgis0008_shapefile_tl2000_us_tract_1980/US_tract_1980.shp")

data_1980 <- read_csv("../../data/time-series/1980csv/nhgis0010_ds104_1980_tract.csv")
data2_1980 <- read_csv("../../data/time-series/1980csv/nhgis0010_ds116_1980_tract.csv")

#str(tracts_1980)
#str(data_1980)
```


```{r, message=F, warning=F}
race_1980 <- data_1980 %>%
  mutate(
    total = C9D001 + C9D002 + C9D003 + C9D004 + C9D005 +
            C9D006 + C9D007 + C9D008 + C9D009 + C9D010 +
            C9D011 + C9D012 + C9D013 + C9D014 + C9D015,

    white = C9D001,
    black = C9D002,

    pct_black = black / total
  )
```


```{r, message=F, warning=F}
race_1980_mobile <- race_1980 %>%
  filter(STATEA == "01", COUNTYA == "097")
```

```{r}

data_1980 %>%
  select(C6X001, C6X002, C6X003) %>%
  summary()



data_1980 %>%
  mutate(test = C6X002 / C6X001) %>%
  summarise(max(test, na.rm = TRUE))

```


```{r, message=F, warning=F}
ggplot(race_1980_mobile) +
  geom_sf(aes(fill = pct_black), color = NA) +
  scale_fill_viridis_c(
    option = "magma",
    limits = c(0, 1),
    labels = scales::percent_format()
  ) +
  labs(
    title = "Mobile County, AL (1980)",
    fill = "% Black"
  ) +
  theme_minimal()
```

## Trying different 1980 tract-level data set

```{r, message=F, warning=F}
data2_1980 <- data2_1980 %>%
  mutate(
    total = C6X001 + C6X002 + C6X003 + C6X004 + C6X005,
    black = C6X002,
    pct_black = ifelse(total > 0, black / total, NA_real_)
  )

summary(data2_1980$pct_black)
```


```{r, message=F, warning=F}

race2_1980 <- tracts_1980 %>%
  left_join(data2_1980, by = "GISJOIN") %>%
  filter(STATEA == "01", COUNTYA == "097")

saveRDS(race2_1980, "../../data/time-series/1980_race_map.rds")

ggplot(race2_1980) +
  geom_sf(aes(fill = pct_black), color = NA) +
  scale_fill_viridis_c(
    option = "magma",
    limits = c(0, 1),
    labels = scales::percent_format(accuracy = 1),
    guide = guide_colorbar(
      barwidth = 0.7,
      barheight = 6
    )
  ) +
  labs(
    title = "Mobile County, AL (1980)",
    fill = "% Black"
  ) +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank()
  )
```

```{r, eval=F, message=F, warning=F}

library(dplyr)

B <- sum(race2_1980$black, na.rm = TRUE)
W <- sum(race2_1980$white, na.rm = TRUE)

d_1980 <- race2_1980 %>%
  mutate(
    black_share = black / B,
    white_share = white / W,
    diff = abs(black_share - white_share)
  ) %>%
  summarise(D = 0.5 * sum(diff, na.rm = TRUE))

d_1980$D
```


```{r, message=F, warning=F}

ggplot(race2_1980) +
  geom_sf(aes(fill = pct_black), color = NA) +
  scale_fill_viridis_c(
    option = "magma",
    limits = c(0, 1),
    labels = scales::percent_format(accuracy = 1),
    guide = guide_colorbar(
      barwidth = 0.7,
      barheight = 6
    )
  ) +
  labs(
    title = "Mobile County, AL (1980)",
    subtitle = "Index of Dissimilarity = 0.771",
    fill = "% Black"
  ) +
  coord_sf(expand = FALSE) +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    legend.position = "right",
    legend.box = "vertical",
    plot.margin = margin(5, 5, 5, 5)
  )
```


```{r, message=F, warning=F}


```


```{r, message=F, warning=F}


```


```{r, message=F, warning=F}


```



